language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build mailslurp_client.gemspec
  - gem install ./mailslurp_client-7.0.8.gem
