=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSlurpClient::ApiAuditLogControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApiAuditLogControllerApi' do
  before do
    # run before each test
    @api_instance = MailSlurpClient::ApiAuditLogControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiAuditLogControllerApi' do
    it 'should create an instance of ApiAuditLogControllerApi' do
      expect(@api_instance).to be_instance_of(MailSlurpClient::ApiAuditLogControllerApi)
    end
  end

  # unit tests for get_audit_log_by_event_id
  # @param event_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :since 
  # @option opts [DateTime] :before 
  # @return [AuditLogEventDto]
  describe 'get_audit_log_by_event_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_audit_logs
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :since 
  # @option opts [DateTime] :before 
  # @option opts [String] :action 
  # @option opts [String] :user_id 
  # @option opts [String] :actor_user_id 
  # @option opts [String] :target_user_id 
  # @option opts [String] :resource_type 
  # @option opts [String] :resource_id 
  # @option opts [String] :outcome 
  # @option opts [String] :request_id 
  # @option opts [String] :ip_address 
  # @option opts [Integer] :page_size 
  # @option opts [String] :cursor 
  # @return [AuditLogPageDto]
  describe 'get_audit_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_audit_logs
  # @param audit_log_search_options 
  # @param [Hash] opts the optional parameters
  # @return [AuditLogPageDto]
  describe 'search_audit_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
