=begin
#MailSlurp API

### Introduction  [MailSlurp](https://www.mailslurp.com) is an Email API for developers and QA testers. It let's users: - create emails addresses on demand - receive emails and attachments in code - send templated HTML emails  ## About  This page contains the REST API documentation for MailSlurp. All requests require API Key authentication passed as an `x-api-key` header.  Create an account to [get your free API Key](https://app.mailslurp.com/sign-up/).  ## Resources - 🔑 [Get API Key](https://app.mailslurp.com/sign-up/)                    - 🎓 [Developer Portal](https://www.mailslurp.com/docs/)           - 📦 [Library SDKs](https://www.mailslurp.com/docs/) - ✍️ [Code Examples](https://www.mailslurp.com/examples) - ⚠️ [Report an issue](https://drift.me/mailslurp)  ## Explore  

The version of the OpenAPI document: 6.5.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSlurpClient::BulkActionsControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BulkActionsControllerApi' do
  before do
    # run before each test
    @api_instance = MailSlurpClient::BulkActionsControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BulkActionsControllerApi' do
    it 'should create an instance of BulkActionsControllerApi' do
      expect(@api_instance).to be_instance_of(MailSlurpClient::BulkActionsControllerApi)
    end
  end

  # unit tests for bulk_create_inboxes
  # Bulk create Inboxes (email addresses)
  # Enterprise Plan Required
  # @param count Number of inboxes to be created in bulk
  # @param [Hash] opts the optional parameters
  # @return [Array<Inbox>]
  describe 'bulk_create_inboxes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bulk_delete_inboxes
  # Bulk Delete Inboxes
  # Enterprise Plan Required
  # @param ids ids
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'bulk_delete_inboxes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bulk_send_emails
  # Bulk Send Emails
  # Enterprise Plan Required
  # @param bulk_send_email_options bulkSendEmailOptions
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'bulk_send_emails test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
