=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSlurpClient::DomainMonitorControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DomainMonitorControllerApi' do
  before do
    # run before each test
    @api_instance = MailSlurpClient::DomainMonitorControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainMonitorControllerApi' do
    it 'should create an instance of DomainMonitorControllerApi' do
      expect(@api_instance).to be_instance_of(MailSlurpClient::DomainMonitorControllerApi)
    end
  end

  # unit tests for create_domain_monitor
  # Create domain monitor
  # @param create_domain_monitor_options 
  # @param [Hash] opts the optional parameters
  # @return [DomainMonitorDto]
  describe 'create_domain_monitor test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_domain_monitor_alert_sink
  # Create alert sink for monitor
  # @param monitor_id 
  # @param create_domain_monitor_alert_sink_options 
  # @param [Hash] opts the optional parameters
  # @return [DomainMonitorAlertSinkDto]
  describe 'create_domain_monitor_alert_sink test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_domain_monitor
  # Delete domain monitor
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_domain_monitor test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_domain_monitor_alert_sink
  # Delete monitor alert sink
  # @param monitor_id 
  # @param sink_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_domain_monitor_alert_sink test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitor
  # Get domain monitor
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @return [DomainMonitorDto]
  describe 'get_domain_monitor test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitor_alert_sinks
  # List alert sinks for monitor
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<DomainMonitorAlertSinkDto>]
  describe 'get_domain_monitor_alert_sinks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitor_insights
  # Get monitor insights
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :since 
  # @option opts [DateTime] :before 
  # @return [DomainMonitorInsightsDto]
  describe 'get_domain_monitor_insights test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitor_runs
  # List monitor runs
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :since 
  # @option opts [DateTime] :before 
  # @option opts [String] :status 
  # @option opts [Integer] :limit 
  # @return [Array<DomainMonitorRunDto>]
  describe 'get_domain_monitor_runs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitor_series
  # Get monitor trend series
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :since 
  # @option opts [DateTime] :before 
  # @option opts [String] :bucket 
  # @return [DomainMonitorSeriesDto]
  describe 'get_domain_monitor_series test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_domain_monitors
  # List domain monitors
  # @param [Hash] opts the optional parameters
  # @return [Array<DomainMonitorDto>]
  describe 'get_domain_monitors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for run_domain_monitor_now
  # Run monitor now
  # @param monitor_id 
  # @param [Hash] opts the optional parameters
  # @return [DomainMonitorRunNowResult]
  describe 'run_domain_monitor_now test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for run_due_domain_monitors
  # Run due monitors for user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :max_runs 
  # @return [DomainMonitorRunDueResult]
  describe 'run_due_domain_monitors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_domain_monitor
  # Update domain monitor
  # @param monitor_id 
  # @param update_domain_monitor_options 
  # @param [Hash] opts the optional parameters
  # @return [DomainMonitorDto]
  describe 'update_domain_monitor test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
