=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module MailSlurpClient
  class CreatePhoneNumberOptions
    attr_accessor :phone_country

    attr_accessor :name

    attr_accessor :description

    attr_accessor :tags

    attr_accessor :schedule

    attr_accessor :phone_number_endpoint_override

    attr_accessor :phone_number_variant

    attr_accessor :phone_provider

    # Line-quality preference for simple phone number provisioning
    attr_accessor :phone_line_filter

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'phone_country' => :'phoneCountry',
        :'name' => :'name',
        :'description' => :'description',
        :'tags' => :'tags',
        :'schedule' => :'schedule',
        :'phone_number_endpoint_override' => :'phoneNumberEndpointOverride',
        :'phone_number_variant' => :'phoneNumberVariant',
        :'phone_provider' => :'phoneProvider',
        :'phone_line_filter' => :'phoneLineFilter'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'phone_country' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'tags' => :'Array<String>',
        :'schedule' => :'String',
        :'phone_number_endpoint_override' => :'String',
        :'phone_number_variant' => :'String',
        :'phone_provider' => :'String',
        :'phone_line_filter' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSlurpClient::CreatePhoneNumberOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSlurpClient::CreatePhoneNumberOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'phone_country')
        self.phone_country = attributes[:'phone_country']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'phone_number_endpoint_override')
        self.phone_number_endpoint_override = attributes[:'phone_number_endpoint_override']
      end

      if attributes.key?(:'phone_number_variant')
        self.phone_number_variant = attributes[:'phone_number_variant']
      end

      if attributes.key?(:'phone_provider')
        self.phone_provider = attributes[:'phone_provider']
      end

      if attributes.key?(:'phone_line_filter')
        self.phone_line_filter = attributes[:'phone_line_filter']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @phone_country.nil?
        invalid_properties.push('invalid value for "phone_country", phone_country cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @phone_country.nil?
      phone_country_validator = EnumAttributeValidator.new('String', ["US", "GB", "AU", "CA", "EE", "HK", "PL", "PT", "NL", "IL", "FI", "SE"])
      return false unless phone_country_validator.valid?(@phone_country)
      schedule_validator = EnumAttributeValidator.new('String', ["MONTHLY", "YEARLY"])
      return false unless schedule_validator.valid?(@schedule)
      phone_number_variant_validator = EnumAttributeValidator.new('String', ["LOCAL", "MOBILE", "TOLL_FREE"])
      return false unless phone_number_variant_validator.valid?(@phone_number_variant)
      phone_provider_validator = EnumAttributeValidator.new('String', ["T1", "T2"])
      return false unless phone_provider_validator.valid?(@phone_provider)
      phone_line_filter_validator = EnumAttributeValidator.new('String', ["ANY", "OTP_FRIENDLY", "NON_VOIP"])
      return false unless phone_line_filter_validator.valid?(@phone_line_filter)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_country Object to be assigned
    def phone_country=(phone_country)
      validator = EnumAttributeValidator.new('String', ["US", "GB", "AU", "CA", "EE", "HK", "PL", "PT", "NL", "IL", "FI", "SE"])
      unless validator.valid?(phone_country)
        fail ArgumentError, "invalid value for \"phone_country\", must be one of #{validator.allowable_values}."
      end
      @phone_country = phone_country
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] schedule Object to be assigned
    def schedule=(schedule)
      validator = EnumAttributeValidator.new('String', ["MONTHLY", "YEARLY"])
      unless validator.valid?(schedule)
        fail ArgumentError, "invalid value for \"schedule\", must be one of #{validator.allowable_values}."
      end
      @schedule = schedule
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_variant Object to be assigned
    def phone_number_variant=(phone_number_variant)
      validator = EnumAttributeValidator.new('String', ["LOCAL", "MOBILE", "TOLL_FREE"])
      unless validator.valid?(phone_number_variant)
        fail ArgumentError, "invalid value for \"phone_number_variant\", must be one of #{validator.allowable_values}."
      end
      @phone_number_variant = phone_number_variant
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_provider Object to be assigned
    def phone_provider=(phone_provider)
      validator = EnumAttributeValidator.new('String', ["T1", "T2"])
      unless validator.valid?(phone_provider)
        fail ArgumentError, "invalid value for \"phone_provider\", must be one of #{validator.allowable_values}."
      end
      @phone_provider = phone_provider
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_line_filter Object to be assigned
    def phone_line_filter=(phone_line_filter)
      validator = EnumAttributeValidator.new('String', ["ANY", "OTP_FRIENDLY", "NON_VOIP"])
      unless validator.valid?(phone_line_filter)
        fail ArgumentError, "invalid value for \"phone_line_filter\", must be one of #{validator.allowable_values}."
      end
      @phone_line_filter = phone_line_filter
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          phone_country == o.phone_country &&
          name == o.name &&
          description == o.description &&
          tags == o.tags &&
          schedule == o.schedule &&
          phone_number_endpoint_override == o.phone_number_endpoint_override &&
          phone_number_variant == o.phone_number_variant &&
          phone_provider == o.phone_provider &&
          phone_line_filter == o.phone_line_filter
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [phone_country, name, description, tags, schedule, phone_number_endpoint_override, phone_number_variant, phone_provider, phone_line_filter].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        MailSlurpClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
