=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module MailSlurpClient
  class GenerateSpfRecordOptions
    # Domain the SPF record applies to
    attr_accessor :domain

    # Optional include domains
    attr_accessor :include_domains

    # Optional IPv4 CIDRs or hosts
    attr_accessor :ip4

    # Optional IPv6 CIDRs or hosts
    attr_accessor :ip6

    # Whether to include the MX mechanism
    attr_accessor :mx

    # Whether to include the A mechanism
    attr_accessor :a

    attr_accessor :all_policy

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'domain' => :'domain',
        :'include_domains' => :'includeDomains',
        :'ip4' => :'ip4',
        :'ip6' => :'ip6',
        :'mx' => :'mx',
        :'a' => :'a',
        :'all_policy' => :'allPolicy'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'domain' => :'String',
        :'include_domains' => :'Array<String>',
        :'ip4' => :'Array<String>',
        :'ip6' => :'Array<String>',
        :'mx' => :'Boolean',
        :'a' => :'Boolean',
        :'all_policy' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'include_domains',
        :'ip4',
        :'ip6',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSlurpClient::GenerateSpfRecordOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSlurpClient::GenerateSpfRecordOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'include_domains')
        if (value = attributes[:'include_domains']).is_a?(Array)
          self.include_domains = value
        end
      end

      if attributes.key?(:'ip4')
        if (value = attributes[:'ip4']).is_a?(Array)
          self.ip4 = value
        end
      end

      if attributes.key?(:'ip6')
        if (value = attributes[:'ip6']).is_a?(Array)
          self.ip6 = value
        end
      end

      if attributes.key?(:'mx')
        self.mx = attributes[:'mx']
      end

      if attributes.key?(:'a')
        self.a = attributes[:'a']
      end

      if attributes.key?(:'all_policy')
        self.all_policy = attributes[:'all_policy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @domain.to_s.length > 253
        invalid_properties.push('invalid value for "domain", the character length must be smaller than or equal to 253.')
      end

      if @domain.to_s.length < 0
        invalid_properties.push('invalid value for "domain", the character length must be great than or equal to 0.')
      end

      if @mx.nil?
        invalid_properties.push('invalid value for "mx", mx cannot be nil.')
      end

      if @a.nil?
        invalid_properties.push('invalid value for "a", a cannot be nil.')
      end

      if @all_policy.nil?
        invalid_properties.push('invalid value for "all_policy", all_policy cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @domain.nil?
      return false if @domain.to_s.length > 253
      return false if @domain.to_s.length < 0
      return false if @mx.nil?
      return false if @a.nil?
      return false if @all_policy.nil?
      all_policy_validator = EnumAttributeValidator.new('String', ["FAIL", "SOFTFAIL", "NEUTRAL"])
      return false unless all_policy_validator.valid?(@all_policy)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      if domain.to_s.length > 253
        fail ArgumentError, 'invalid value for "domain", the character length must be smaller than or equal to 253.'
      end

      if domain.to_s.length < 0
        fail ArgumentError, 'invalid value for "domain", the character length must be great than or equal to 0.'
      end

      @domain = domain
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] all_policy Object to be assigned
    def all_policy=(all_policy)
      validator = EnumAttributeValidator.new('String', ["FAIL", "SOFTFAIL", "NEUTRAL"])
      unless validator.valid?(all_policy)
        fail ArgumentError, "invalid value for \"all_policy\", must be one of #{validator.allowable_values}."
      end
      @all_policy = all_policy
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          domain == o.domain &&
          include_domains == o.include_domains &&
          ip4 == o.ip4 &&
          ip6 == o.ip6 &&
          mx == o.mx &&
          a == o.a &&
          all_policy == o.all_policy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [domain, include_domains, ip4, ip6, mx, a, all_policy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        MailSlurpClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
