=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module MailSlurpClient
  class ImapMailboxStatus
    # The mailbox name.
    attr_accessor :name

    # True if the mailbox is open in read-only mode.
    attr_accessor :read_only

    # Results map
    attr_accessor :items

    # The mailbox flags.
    attr_accessor :flags

    # The mailbox permanent flags.
    attr_accessor :permanent_flags

    # The sequence number of the first unseen message in the mailbox.
    attr_accessor :unseen_seq_num

    # The number of messages in this mailbox.
    attr_accessor :messages

    # The number of messages not seen since the last time the mailbox was opened.
    attr_accessor :recent

    # The number of unread messages.
    attr_accessor :unseen

    # The next UID.
    attr_accessor :uid_next

    # Together with a UID, it is a unique identifier for a message. Must be greater than or equal to 1.
    attr_accessor :uid_validity

    # Per-mailbox limit of message size. Set only if server supports the APPENDLIMIT extension
    attr_accessor :append_limit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'read_only' => :'readOnly',
        :'items' => :'items',
        :'flags' => :'flags',
        :'permanent_flags' => :'permanentFlags',
        :'unseen_seq_num' => :'unseenSeqNum',
        :'messages' => :'messages',
        :'recent' => :'recent',
        :'unseen' => :'unseen',
        :'uid_next' => :'uidNext',
        :'uid_validity' => :'uidValidity',
        :'append_limit' => :'appendLimit'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'read_only' => :'Boolean',
        :'items' => :'Hash<String, Object>',
        :'flags' => :'Array<String>',
        :'permanent_flags' => :'Array<String>',
        :'unseen_seq_num' => :'Integer',
        :'messages' => :'Integer',
        :'recent' => :'Integer',
        :'unseen' => :'Integer',
        :'uid_next' => :'Integer',
        :'uid_validity' => :'Integer',
        :'append_limit' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'items',
        :'flags',
        :'permanent_flags',
        :'append_limit'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSlurpClient::ImapMailboxStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSlurpClient::ImapMailboxStatus`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'read_only')
        self.read_only = attributes[:'read_only']
      end

      if attributes.key?(:'items')
        if (value = attributes[:'items']).is_a?(Hash)
          self.items = value
        end
      end

      if attributes.key?(:'flags')
        if (value = attributes[:'flags']).is_a?(Array)
          self.flags = value
        end
      end

      if attributes.key?(:'permanent_flags')
        if (value = attributes[:'permanent_flags']).is_a?(Array)
          self.permanent_flags = value
        end
      end

      if attributes.key?(:'unseen_seq_num')
        self.unseen_seq_num = attributes[:'unseen_seq_num']
      end

      if attributes.key?(:'messages')
        self.messages = attributes[:'messages']
      end

      if attributes.key?(:'recent')
        self.recent = attributes[:'recent']
      end

      if attributes.key?(:'unseen')
        self.unseen = attributes[:'unseen']
      end

      if attributes.key?(:'uid_next')
        self.uid_next = attributes[:'uid_next']
      end

      if attributes.key?(:'uid_validity')
        self.uid_validity = attributes[:'uid_validity']
      end

      if attributes.key?(:'append_limit')
        self.append_limit = attributes[:'append_limit']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @read_only.nil?
        invalid_properties.push('invalid value for "read_only", read_only cannot be nil.')
      end

      if @unseen_seq_num.nil?
        invalid_properties.push('invalid value for "unseen_seq_num", unseen_seq_num cannot be nil.')
      end

      if @messages.nil?
        invalid_properties.push('invalid value for "messages", messages cannot be nil.')
      end

      if @recent.nil?
        invalid_properties.push('invalid value for "recent", recent cannot be nil.')
      end

      if @unseen.nil?
        invalid_properties.push('invalid value for "unseen", unseen cannot be nil.')
      end

      if @uid_next.nil?
        invalid_properties.push('invalid value for "uid_next", uid_next cannot be nil.')
      end

      if @uid_validity.nil?
        invalid_properties.push('invalid value for "uid_validity", uid_validity cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @read_only.nil?
      return false if @unseen_seq_num.nil?
      return false if @messages.nil?
      return false if @recent.nil?
      return false if @unseen.nil?
      return false if @uid_next.nil?
      return false if @uid_validity.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          read_only == o.read_only &&
          items == o.items &&
          flags == o.flags &&
          permanent_flags == o.permanent_flags &&
          unseen_seq_num == o.unseen_seq_num &&
          messages == o.messages &&
          recent == o.recent &&
          unseen == o.unseen &&
          uid_next == o.uid_next &&
          uid_validity == o.uid_validity &&
          append_limit == o.append_limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, read_only, items, flags, permanent_flags, unseen_seq_num, messages, recent, unseen, uid_next, uid_validity, append_limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        MailSlurpClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
