=begin
#MailSlurp API

#MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository

The version of the OpenAPI document: 6.5.2
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module MailSlurpClient
  class InvokeTransformerOptions
    attr_accessor :ai_transform_id

    attr_accessor :ai_transform_mapping_id

    attr_accessor :raw_input

    attr_accessor :entity_id

    attr_accessor :entity_type

    attr_accessor :raw_conditions

    attr_accessor :raw_instructions

    attr_accessor :raw_output_schema

    attr_accessor :content_selector

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ai_transform_id' => :'aiTransformId',
        :'ai_transform_mapping_id' => :'aiTransformMappingId',
        :'raw_input' => :'rawInput',
        :'entity_id' => :'entityId',
        :'entity_type' => :'entityType',
        :'raw_conditions' => :'rawConditions',
        :'raw_instructions' => :'rawInstructions',
        :'raw_output_schema' => :'rawOutputSchema',
        :'content_selector' => :'contentSelector'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ai_transform_id' => :'String',
        :'ai_transform_mapping_id' => :'String',
        :'raw_input' => :'String',
        :'entity_id' => :'String',
        :'entity_type' => :'String',
        :'raw_conditions' => :'Array<String>',
        :'raw_instructions' => :'Array<String>',
        :'raw_output_schema' => :'StructuredOutputSchema',
        :'content_selector' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'raw_output_schema',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSlurpClient::InvokeTransformerOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSlurpClient::InvokeTransformerOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ai_transform_id')
        self.ai_transform_id = attributes[:'ai_transform_id']
      end

      if attributes.key?(:'ai_transform_mapping_id')
        self.ai_transform_mapping_id = attributes[:'ai_transform_mapping_id']
      end

      if attributes.key?(:'raw_input')
        self.raw_input = attributes[:'raw_input']
      end

      if attributes.key?(:'entity_id')
        self.entity_id = attributes[:'entity_id']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'raw_conditions')
        if (value = attributes[:'raw_conditions']).is_a?(Array)
          self.raw_conditions = value
        end
      end

      if attributes.key?(:'raw_instructions')
        if (value = attributes[:'raw_instructions']).is_a?(Array)
          self.raw_instructions = value
        end
      end

      if attributes.key?(:'raw_output_schema')
        self.raw_output_schema = attributes[:'raw_output_schema']
      end

      if attributes.key?(:'content_selector')
        self.content_selector = attributes[:'content_selector']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      entity_type_validator = EnumAttributeValidator.new('String', ["EMAIL", "SMS", "ATTACHMENT"])
      return false unless entity_type_validator.valid?(@entity_type)
      content_selector_validator = EnumAttributeValidator.new('String', ["RAW", "BODY", "BODY_ATTACHMENTS"])
      return false unless content_selector_validator.valid?(@content_selector)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] entity_type Object to be assigned
    def entity_type=(entity_type)
      validator = EnumAttributeValidator.new('String', ["EMAIL", "SMS", "ATTACHMENT"])
      unless validator.valid?(entity_type)
        fail ArgumentError, "invalid value for \"entity_type\", must be one of #{validator.allowable_values}."
      end
      @entity_type = entity_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] content_selector Object to be assigned
    def content_selector=(content_selector)
      validator = EnumAttributeValidator.new('String', ["RAW", "BODY", "BODY_ATTACHMENTS"])
      unless validator.valid?(content_selector)
        fail ArgumentError, "invalid value for \"content_selector\", must be one of #{validator.allowable_values}."
      end
      @content_selector = content_selector
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ai_transform_id == o.ai_transform_id &&
          ai_transform_mapping_id == o.ai_transform_mapping_id &&
          raw_input == o.raw_input &&
          entity_id == o.entity_id &&
          entity_type == o.entity_type &&
          raw_conditions == o.raw_conditions &&
          raw_instructions == o.raw_instructions &&
          raw_output_schema == o.raw_output_schema &&
          content_selector == o.content_selector
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ai_transform_id, ai_transform_mapping_id, raw_input, entity_id, entity_type, raw_conditions, raw_instructions, raw_output_schema, content_selector].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        MailSlurpClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
