=begin
#MailSlurp API

#For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).

OpenAPI spec version: 0.0.1-alpha
Contact: contact@mailslurp.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

# Common files
require 'mailslurp_client/api_client'
require 'mailslurp_client/api_error'
require 'mailslurp_client/version'
require 'mailslurp_client/configuration'

# Models
require 'mailslurp_client/models/basic_auth_options'
require 'mailslurp_client/models/bulk_send_email_options'
require 'mailslurp_client/models/create_webhook_options'
require 'mailslurp_client/models/email'
require 'mailslurp_client/models/email_analysis'
require 'mailslurp_client/models/email_preview'
require 'mailslurp_client/models/inbox'
require 'mailslurp_client/models/send_email_options'
require 'mailslurp_client/models/webhook'

# APIs
require 'mailslurp_client/api/common_operations_api'
require 'mailslurp_client/api/extra_operations_api'

module MailSlurpClient
  class << self
    # Customize default settings for the SDK using block.
    #   MailSlurpClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
